with-expecter: True
resolve-type-alias: False
disable-version-string: True
issue-845-fix: True
log-level: info
packages:
    github.com/guiyomh/aicommitter/internal/domain/utils:
        config:
            all: true
            dir: "internal/mocks/domain/utils"
    github.com/guiyomh/aicommitter/internal/domain/services:
        config:
            all: true
            dir: "internal/mocks/services"
