version: "3"

env:
  CGO_ENABLED: "0"

vars:
  BIN: "{{.ROOT_DIR}}/bin"
  BUILD: "{{.ROOT_DIR}}/.build"

tasks:
  # default:
  #   cmds:
  #     - task: lint
  #     - task: test

  install:
    desc: Installs aicommitter
    aliases: [i]
    sources:
      - "./**/*.go"
    cmds:
      - task: wire
      - go install -v ./cmd/aicommitter

  setup:
    desc: Install tools needed for development
    cmds:
      - task: install:mockery
      - task: install:golangci-lint
      - task: install:gotestsum
      - task: install:wire
      - task: wire
      - task: mocks:generate

  install:mockery:
    desc: Installs mockgen; a tool to generate mock files
    internal: true
    vars:
      MOCKERY_VERSION: v2.53.0
    env:
      GOBIN: "{{.BIN}}"
    status:
      - go version -m {{.BIN}}/mockery | grep github.com/vektra/mockery | grep {{.MOCKERY_VERSION}}
    cmds:
      - go install github.com/vektra/mockery/v2@{{.MOCKERY_VERSION}}

  install:gotestsum:
    desc: Installs gotestsum; a test runner
    internal: true
    vars:
      GOTESTSUM_VERSION: v1.12.0
    env:
      GOBIN: "{{.BIN}}"
    status:
      - go version -m {{.BIN}}/gotestsum | grep gotest.tools/gotestsum | grep {{.GOTESTSUM_VERSION}}
    cmds:
      - go install gotest.tools/gotestsum@{{.GOTESTSUM_VERSION}}

  install:golangci-lint:
    desc: Installs golangci-lint
    internal: true
    vars:
      GOLANGCI_LINT_VERSION: v1.60.3
    env:
      GOBIN: "{{.BIN}}"
    status:
      - go version -m {{.BIN}}/golangci-lint | grep github.com/golangci/golangci-lint | grep {{.GOLANGCI_LINT_VERSION}}
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}

  install:wire:
    desc: Installs wire; a code generation tool
    internal: true
    vars:
      WIRE_VERSION: v0.6.0
    env:
      GOBIN: "{{.BIN}}"
    status:
      - go version -m {{.BIN}}/wire | grep github.com/google/wire | grep {{.WIRE_VERSION}}
    cmds:
      - go install github.com/google/wire/cmd/wire@{{.WIRE_VERSION}}

  lint:
    desc: Runs golangci-lint
    aliases: [l]
    sources:
      - "./**/*.go"
      - .golangci.yml
    cmds:
      - "{{.BIN}}/golangci-lint run"

  lint:fix:
    desc: Runs golangci-lint and fixes any issues
    sources:
      - "./**/*.go"
      - .golangci.yml
    cmds:
      - "{{.BIN}}/golangci-lint run --fix"
  
  wire: 
    desc: Runs wire
    aliases: [w]
    cmds:
      - "{{.BIN}}/wire ./internal"

  test:
    desc: Runs test suite
    aliases: [t]
    deps: [install]
    cmds:
      - "mkdir -p {{.BUILD}}"
      - "{{.BIN}}/gotestsum --format testname -- -v -coverprofile={{.BUILD}}/coverage.txt {{catLines .GO_PACKAGES}}"
    vars:
      GO_PACKAGES:
        sh: go list ./...

  run:
    desc: Runs aicommitter
    aliases: [r]
    deps: [install]
    dotenv:
      - .env
    cmds:
      - aicommitter
  
  mocks:generate:
    desc: generate mock files
    cmds:
      - "{{.BIN}}/mockery"

  mocks:remove:
    desc: remove all mock files
    cmds:
      - find . -name '*_mock.go' -o -name 'mock_*_test.go' | xargs -r rm
      - rm -rf internal/mocks/
