// Code generated by mockery. DO NOT EDIT.

package conventionalcommit

import (
	conventionalcommit "github.com/guiyomh/aicommitter/pkg/conventionalcommit"
	mock "github.com/stretchr/testify/mock"
)

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: message
func (_m *MockParser) Parse(message string) (*conventionalcommit.Commit, error) {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *conventionalcommit.Commit
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*conventionalcommit.Commit, error)); ok {
		return rf(message)
	}
	if rf, ok := ret.Get(0).(func(string) *conventionalcommit.Commit); ok {
		r0 = rf(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*conventionalcommit.Commit)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - message string
func (_e *MockParser_Expecter) Parse(message interface{}) *MockParser_Parse_Call {
	return &MockParser_Parse_Call{Call: _e.mock.On("Parse", message)}
}

func (_c *MockParser_Parse_Call) Run(run func(message string)) *MockParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockParser_Parse_Call) Return(_a0 *conventionalcommit.Commit, _a1 error) *MockParser_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParser_Parse_Call) RunAndReturn(run func(string) (*conventionalcommit.Commit, error)) *MockParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
