// Code generated by mockery. DO NOT EDIT.

package utils

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, cmd, args
func (_m *MockExecutor) Execute(ctx context.Context, cmd string, args ...string) (string, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, cmd)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) (string, error)); ok {
		return rf(ctx, cmd, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) string); ok {
		r0 = rf(ctx, cmd, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = rf(ctx, cmd, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd string
//   - args ...string
func (_e *MockExecutor_Expecter) Execute(ctx interface{}, cmd interface{}, args ...interface{}) *MockExecutor_Execute_Call {
	return &MockExecutor_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{ctx, cmd}, args...)...)}
}

func (_c *MockExecutor_Execute_Call) Run(run func(ctx context.Context, cmd string, args ...string)) *MockExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockExecutor_Execute_Call) Return(_a0 string, _a1 error) *MockExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutor_Execute_Call) RunAndReturn(run func(context.Context, string, ...string) (string, error)) *MockExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteWithEnv provides a mock function with given fields: ctx, env, cmd, args
func (_m *MockExecutor) ExecuteWithEnv(ctx context.Context, env map[string]string, cmd string, args ...string) (string, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, env, cmd)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteWithEnv")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, string, ...string) (string, error)); ok {
		return rf(ctx, env, cmd, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, string, ...string) string); ok {
		r0 = rf(ctx, env, cmd, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string, string, ...string) error); ok {
		r1 = rf(ctx, env, cmd, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutor_ExecuteWithEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteWithEnv'
type MockExecutor_ExecuteWithEnv_Call struct {
	*mock.Call
}

// ExecuteWithEnv is a helper method to define mock.On call
//   - ctx context.Context
//   - env map[string]string
//   - cmd string
//   - args ...string
func (_e *MockExecutor_Expecter) ExecuteWithEnv(ctx interface{}, env interface{}, cmd interface{}, args ...interface{}) *MockExecutor_ExecuteWithEnv_Call {
	return &MockExecutor_ExecuteWithEnv_Call{Call: _e.mock.On("ExecuteWithEnv",
		append([]interface{}{ctx, env, cmd}, args...)...)}
}

func (_c *MockExecutor_ExecuteWithEnv_Call) Run(run func(ctx context.Context, env map[string]string, cmd string, args ...string)) *MockExecutor_ExecuteWithEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(map[string]string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockExecutor_ExecuteWithEnv_Call) Return(_a0 string, _a1 error) *MockExecutor_ExecuteWithEnv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutor_ExecuteWithEnv_Call) RunAndReturn(run func(context.Context, map[string]string, string, ...string) (string, error)) *MockExecutor_ExecuteWithEnv_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
