// Code generated by mockery. DO NOT EDIT.

package services

import (
	config "github.com/guiyomh/aicommitter/internal/domain/config"
	mock "github.com/stretchr/testify/mock"
)

// MockCommitTypeProvider is an autogenerated mock type for the CommitTypeProvider type
type MockCommitTypeProvider struct {
	mock.Mock
}

type MockCommitTypeProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommitTypeProvider) EXPECT() *MockCommitTypeProvider_Expecter {
	return &MockCommitTypeProvider_Expecter{mock: &_m.Mock}
}

// GetCommitTypes provides a mock function with no fields
func (_m *MockCommitTypeProvider) GetCommitTypes() map[string]config.CommitType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCommitTypes")
	}

	var r0 map[string]config.CommitType
	if rf, ok := ret.Get(0).(func() map[string]config.CommitType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]config.CommitType)
		}
	}

	return r0
}

// MockCommitTypeProvider_GetCommitTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommitTypes'
type MockCommitTypeProvider_GetCommitTypes_Call struct {
	*mock.Call
}

// GetCommitTypes is a helper method to define mock.On call
func (_e *MockCommitTypeProvider_Expecter) GetCommitTypes() *MockCommitTypeProvider_GetCommitTypes_Call {
	return &MockCommitTypeProvider_GetCommitTypes_Call{Call: _e.mock.On("GetCommitTypes")}
}

func (_c *MockCommitTypeProvider_GetCommitTypes_Call) Run(run func()) *MockCommitTypeProvider_GetCommitTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommitTypeProvider_GetCommitTypes_Call) Return(_a0 map[string]config.CommitType) *MockCommitTypeProvider_GetCommitTypes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommitTypeProvider_GetCommitTypes_Call) RunAndReturn(run func() map[string]config.CommitType) *MockCommitTypeProvider_GetCommitTypes_Call {
	_c.Call.Return(run)
	return _c
}

// GetTypeDescription provides a mock function with given fields: commitType
func (_m *MockCommitTypeProvider) GetTypeDescription(commitType string) string {
	ret := _m.Called(commitType)

	if len(ret) == 0 {
		panic("no return value specified for GetTypeDescription")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(commitType)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCommitTypeProvider_GetTypeDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTypeDescription'
type MockCommitTypeProvider_GetTypeDescription_Call struct {
	*mock.Call
}

// GetTypeDescription is a helper method to define mock.On call
//   - commitType string
func (_e *MockCommitTypeProvider_Expecter) GetTypeDescription(commitType interface{}) *MockCommitTypeProvider_GetTypeDescription_Call {
	return &MockCommitTypeProvider_GetTypeDescription_Call{Call: _e.mock.On("GetTypeDescription", commitType)}
}

func (_c *MockCommitTypeProvider_GetTypeDescription_Call) Run(run func(commitType string)) *MockCommitTypeProvider_GetTypeDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommitTypeProvider_GetTypeDescription_Call) Return(_a0 string) *MockCommitTypeProvider_GetTypeDescription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommitTypeProvider_GetTypeDescription_Call) RunAndReturn(run func(string) string) *MockCommitTypeProvider_GetTypeDescription_Call {
	_c.Call.Return(run)
	return _c
}

// IsValidType provides a mock function with given fields: commitType
func (_m *MockCommitTypeProvider) IsValidType(commitType string) bool {
	ret := _m.Called(commitType)

	if len(ret) == 0 {
		panic("no return value specified for IsValidType")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(commitType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCommitTypeProvider_IsValidType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValidType'
type MockCommitTypeProvider_IsValidType_Call struct {
	*mock.Call
}

// IsValidType is a helper method to define mock.On call
//   - commitType string
func (_e *MockCommitTypeProvider_Expecter) IsValidType(commitType interface{}) *MockCommitTypeProvider_IsValidType_Call {
	return &MockCommitTypeProvider_IsValidType_Call{Call: _e.mock.On("IsValidType", commitType)}
}

func (_c *MockCommitTypeProvider_IsValidType_Call) Run(run func(commitType string)) *MockCommitTypeProvider_IsValidType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommitTypeProvider_IsValidType_Call) Return(_a0 bool) *MockCommitTypeProvider_IsValidType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommitTypeProvider_IsValidType_Call) RunAndReturn(run func(string) bool) *MockCommitTypeProvider_IsValidType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommitTypeProvider creates a new instance of MockCommitTypeProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommitTypeProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommitTypeProvider {
	mock := &MockCommitTypeProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
