// Code generated by mockery. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// MockPromptGenerator is an autogenerated mock type for the PromptGenerator type
type MockPromptGenerator struct {
	mock.Mock
}

type MockPromptGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPromptGenerator) EXPECT() *MockPromptGenerator_Expecter {
	return &MockPromptGenerator_Expecter{mock: &_m.Mock}
}

// GenerateCommitPrompt provides a mock function with given fields: diff, changedFiles, maxDiffSize
func (_m *MockPromptGenerator) GenerateCommitPrompt(diff string, changedFiles []string, maxDiffSize int) string {
	ret := _m.Called(diff, changedFiles, maxDiffSize)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCommitPrompt")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, []string, int) string); ok {
		r0 = rf(diff, changedFiles, maxDiffSize)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPromptGenerator_GenerateCommitPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCommitPrompt'
type MockPromptGenerator_GenerateCommitPrompt_Call struct {
	*mock.Call
}

// GenerateCommitPrompt is a helper method to define mock.On call
//   - diff string
//   - changedFiles []string
//   - maxDiffSize int
func (_e *MockPromptGenerator_Expecter) GenerateCommitPrompt(diff interface{}, changedFiles interface{}, maxDiffSize interface{}) *MockPromptGenerator_GenerateCommitPrompt_Call {
	return &MockPromptGenerator_GenerateCommitPrompt_Call{Call: _e.mock.On("GenerateCommitPrompt", diff, changedFiles, maxDiffSize)}
}

func (_c *MockPromptGenerator_GenerateCommitPrompt_Call) Run(run func(diff string, changedFiles []string, maxDiffSize int)) *MockPromptGenerator_GenerateCommitPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string), args[2].(int))
	})
	return _c
}

func (_c *MockPromptGenerator_GenerateCommitPrompt_Call) Return(_a0 string) *MockPromptGenerator_GenerateCommitPrompt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPromptGenerator_GenerateCommitPrompt_Call) RunAndReturn(run func(string, []string, int) string) *MockPromptGenerator_GenerateCommitPrompt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPromptGenerator creates a new instance of MockPromptGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPromptGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPromptGenerator {
	mock := &MockPromptGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
