// Code generated by mockery. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// MockDiffFormatter is an autogenerated mock type for the DiffFormatter type
type MockDiffFormatter struct {
	mock.Mock
}

type MockDiffFormatter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDiffFormatter) EXPECT() *MockDiffFormatter_Expecter {
	return &MockDiffFormatter_Expecter{mock: &_m.Mock}
}

// FormatDiff provides a mock function with given fields: diff, maxSize
func (_m *MockDiffFormatter) FormatDiff(diff string, maxSize int) string {
	ret := _m.Called(diff, maxSize)

	if len(ret) == 0 {
		panic("no return value specified for FormatDiff")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, int) string); ok {
		r0 = rf(diff, maxSize)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDiffFormatter_FormatDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FormatDiff'
type MockDiffFormatter_FormatDiff_Call struct {
	*mock.Call
}

// FormatDiff is a helper method to define mock.On call
//   - diff string
//   - maxSize int
func (_e *MockDiffFormatter_Expecter) FormatDiff(diff interface{}, maxSize interface{}) *MockDiffFormatter_FormatDiff_Call {
	return &MockDiffFormatter_FormatDiff_Call{Call: _e.mock.On("FormatDiff", diff, maxSize)}
}

func (_c *MockDiffFormatter_FormatDiff_Call) Run(run func(diff string, maxSize int)) *MockDiffFormatter_FormatDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockDiffFormatter_FormatDiff_Call) Return(_a0 string) *MockDiffFormatter_FormatDiff_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDiffFormatter_FormatDiff_Call) RunAndReturn(run func(string, int) string) *MockDiffFormatter_FormatDiff_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileList provides a mock function with given fields: files
func (_m *MockDiffFormatter) GetFileList(files []string) string {
	ret := _m.Called(files)

	if len(ret) == 0 {
		panic("no return value specified for GetFileList")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func([]string) string); ok {
		r0 = rf(files)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDiffFormatter_GetFileList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileList'
type MockDiffFormatter_GetFileList_Call struct {
	*mock.Call
}

// GetFileList is a helper method to define mock.On call
//   - files []string
func (_e *MockDiffFormatter_Expecter) GetFileList(files interface{}) *MockDiffFormatter_GetFileList_Call {
	return &MockDiffFormatter_GetFileList_Call{Call: _e.mock.On("GetFileList", files)}
}

func (_c *MockDiffFormatter_GetFileList_Call) Run(run func(files []string)) *MockDiffFormatter_GetFileList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockDiffFormatter_GetFileList_Call) Return(_a0 string) *MockDiffFormatter_GetFileList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDiffFormatter_GetFileList_Call) RunAndReturn(run func([]string) string) *MockDiffFormatter_GetFileList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDiffFormatter creates a new instance of MockDiffFormatter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDiffFormatter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDiffFormatter {
	mock := &MockDiffFormatter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
