// Code generated by mockery. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// MockPromptTemplateGenerator is an autogenerated mock type for the PromptTemplateGenerator type
type MockPromptTemplateGenerator struct {
	mock.Mock
}

type MockPromptTemplateGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPromptTemplateGenerator) EXPECT() *MockPromptTemplateGenerator_Expecter {
	return &MockPromptTemplateGenerator_Expecter{mock: &_m.Mock}
}

// GenerateTemplate provides a mock function with given fields: commitTypes
func (_m *MockPromptTemplateGenerator) GenerateTemplate(commitTypes []string) string {
	ret := _m.Called(commitTypes)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTemplate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func([]string) string); ok {
		r0 = rf(commitTypes)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPromptTemplateGenerator_GenerateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTemplate'
type MockPromptTemplateGenerator_GenerateTemplate_Call struct {
	*mock.Call
}

// GenerateTemplate is a helper method to define mock.On call
//   - commitTypes []string
func (_e *MockPromptTemplateGenerator_Expecter) GenerateTemplate(commitTypes interface{}) *MockPromptTemplateGenerator_GenerateTemplate_Call {
	return &MockPromptTemplateGenerator_GenerateTemplate_Call{Call: _e.mock.On("GenerateTemplate", commitTypes)}
}

func (_c *MockPromptTemplateGenerator_GenerateTemplate_Call) Run(run func(commitTypes []string)) *MockPromptTemplateGenerator_GenerateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockPromptTemplateGenerator_GenerateTemplate_Call) Return(_a0 string) *MockPromptTemplateGenerator_GenerateTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPromptTemplateGenerator_GenerateTemplate_Call) RunAndReturn(run func([]string) string) *MockPromptTemplateGenerator_GenerateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPromptTemplateGenerator creates a new instance of MockPromptTemplateGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPromptTemplateGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPromptTemplateGenerator {
	mock := &MockPromptTemplateGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
