// Code generated by mockery. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// MockAIProvider is an autogenerated mock type for the AIProvider type
type MockAIProvider struct {
	mock.Mock
}

type MockAIProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIProvider) EXPECT() *MockAIProvider_Expecter {
	return &MockAIProvider_Expecter{mock: &_m.Mock}
}

// GenerateCommitMessage provides a mock function with given fields: diff, changedFiles
func (_m *MockAIProvider) GenerateCommitMessage(diff string, changedFiles []string) (string, error) {
	ret := _m.Called(diff, changedFiles)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCommitMessage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string) (string, error)); ok {
		return rf(diff, changedFiles)
	}
	if rf, ok := ret.Get(0).(func(string, []string) string); ok {
		r0 = rf(diff, changedFiles)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(diff, changedFiles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIProvider_GenerateCommitMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCommitMessage'
type MockAIProvider_GenerateCommitMessage_Call struct {
	*mock.Call
}

// GenerateCommitMessage is a helper method to define mock.On call
//   - diff string
//   - changedFiles []string
func (_e *MockAIProvider_Expecter) GenerateCommitMessage(diff interface{}, changedFiles interface{}) *MockAIProvider_GenerateCommitMessage_Call {
	return &MockAIProvider_GenerateCommitMessage_Call{Call: _e.mock.On("GenerateCommitMessage", diff, changedFiles)}
}

func (_c *MockAIProvider_GenerateCommitMessage_Call) Run(run func(diff string, changedFiles []string)) *MockAIProvider_GenerateCommitMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *MockAIProvider_GenerateCommitMessage_Call) Return(_a0 string, _a1 error) *MockAIProvider_GenerateCommitMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIProvider_GenerateCommitMessage_Call) RunAndReturn(run func(string, []string) (string, error)) *MockAIProvider_GenerateCommitMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAIProvider creates a new instance of MockAIProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIProvider {
	mock := &MockAIProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
